### ISSUE TITLE
好像无法编译啊

### ISSUE THREAD

**Issue by ShuYuMo2003** [danmaku-here/danmaku-local-cpp_easyX-demo#1]
真的无法编译啊，请求提供 easyX 的版本号。 /kel

**Comment by zsh2517** [comment]
刚才测试了一下，使用 VS 2019（版本号 16.7.5） + [EasyX 2020春分版 2020-9-2](https://easyx.cn/downloads/view.aspx?id=10) 是可以正常编译的，能麻烦提供一下编译失败的信息吗？
如果是指的无法按照期望运行，但编译正常，是因为代码中用到的服务器已经关闭，可以用 doc.zsh2517.com 房间号 123 进行测试。后端地址为 http://doc.zsh2517.com/back/get.php?roomid=123 （这里涉及到一步 base64 代码中未实现，因此弹幕为 base64 消息）

**Comment by ShuYuMo2003** [comment]
不好意思，我自己环境有问题，现在可以正常编译了。谢谢大佬。

**Comment by ShuYuMo2003** [comment]
我本机SDK报错……没C++搞过开发QAQ /kel
